### ISSUE TITLE
Run tests using multiple github runners

### ISSUE THREAD

**Issue by sp1thas** [sp1thas/dropboxignore#28]
Both unit and integration tests, should be executed in more than one operating system, in particular, should be executed using the following runners: `ubuntu-22.04`, `ubuntu-20.04`, `macos-12`, `macos-11`

In order to achieve this, `run-on` and `strategy` on `.github/workflows/testing.yaml` should look like this:
```yaml
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04, macos-12, macos-11 ]
```
